// GENERATED by scripts/build-images.mjs — do not edit by hand.
// Regenerate with `npm run images` after changing anything in images-src/.

export interface ImageAsset {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
}

/**
 * Every photograph in the project, keyed by slot.
 *
 * Components read dimensions from here rather than hard-coding them, because
 * `next/image` without explicit width and height lets ScrollTrigger measure
 * against a collapsed box and fire every trigger below it at the wrong offset.
 */
export const IMAGES = {
  "designer-work-1": {
    src: "/images/designers/designer-work-1.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCPOX+S8oAD+kb2GVdFV0/1MTw0pYveMRrlTOGRv55p7N2VSpK6T5IyaMSKOwDDnyhWsUkl0zGEsE4Ez5AAAAA==",
  },
  "designer-work-2": {
    src: "/images/designers/designer-work-2.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCPOX+S8oAD+kb2GVdFV0/1MTw0pYveMRrlTOGRv55p7N2VSpK6T5IyaMSKOwDDnyhWsUkl0zGEsE4Ez5AAAAA==",
  },
  "designer-work-3": {
    src: "/images/designers/designer-work-3.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCPOX+S8oAD+kb2GVdFV0/1MTw0pYveMRrlTOGRv55p7N2VSpK6T5IyaMSKOwDDnyhWsUkl0zGEsE4Ez5AAAAA==",
  },
  "gallery-1": {
    src: "/images/gallery/gallery-1.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAkAA4BaJZgCdAECsHoAAP145FLgUx3fMwO+UDe2Kq5dff2BMjheanpRTa8zy3Sx0/U7XqoVufvd/OSE7jYkmeDZIpuRKvV5XAAA",
  },
  "gallery-2": {
    src: "/images/gallery/gallery-2.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCPOX+S8oAD+kb2GVdFV0/1MTw0pYveMRrlTOGRv55p7N2VSpK6T5IyaMSKOwDDnyhWsUkl0zGEsE4Ez5AAAAA==",
  },
  "gallery-3": {
    src: "/images/gallery/gallery-3.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAkAA4BaJZgCdAECsHoAAP145FLgUx3fMwO+UDe2Kq5dff2BMjheanpRTa8zy3Sx0/U7XqoVufvd/OSE7jYkmeDZIpuRKvV5XAAA",
  },
  "gallery-4": {
    src: "/images/gallery/gallery-4.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCPOX+S8oAD+kb2GVdFV0/1MTw0pYveMRrlTOGRv55p7N2VSpK6T5IyaMSKOwDDnyhWsUkl0zGEsE4Ez5AAAAA==",
  },
  "gallery-5": {
    src: "/images/gallery/gallery-5.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZgCdAYs3DdALRQA/rQgngyPIsu6Sna8Q9ChrHQVdoqk0xbB5HFCSoeMLT6pgHW+NC4ttXXHVEUJk35aDW5FZrvryHX6yhyWgAAA",
  },
  "lifestyle-art": {
    src: "/images/onboarding/lifestyle-art.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZgCdAYs3DdALRQA/rQgngyPIsu6Sna8Q9ChrHQVdoqk0xbB5HFCSoeMLT6pgHW+NC4ttXXHVEUJk35aDW5FZrvryHX6yhyWgAAA",
  },
  "lifestyle-entertaining": {
    src: "/images/onboarding/lifestyle-entertaining.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCPOX+S8oAD+kb2GVdFV0/1MTw0pYveMRrlTOGRv55p7N2VSpK6T5IyaMSKOwDDnyhWsUkl0zGEsE4Ez5AAAAA==",
  },
  "lifestyle-family": {
    src: "/images/onboarding/lifestyle-family.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCPOX+S8oAD+kb2GVdFV0/1MTw0pYveMRrlTOGRv55p7N2VSpK6T5IyaMSKOwDDnyhWsUkl0zGEsE4Ez5AAAAA==",
  },
  "lifestyle-minimal": {
    src: "/images/onboarding/lifestyle-minimal.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZgCdAYs3DdALRQA/rQgngyPIsu6Sna8Q9ChrHQVdoqk0xbB5HFCSoeMLT6pgHW+NC4ttXXHVEUJk35aDW5FZrvryHX6yhyWgAAA",
  },
  "lifestyle-wfh": {
    src: "/images/onboarding/lifestyle-wfh.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAkAA4BaJZgCdAECsHoAAP145FLgUx3fMwO+UDe2Kq5dff2BMjheanpRTa8zy3Sx0/U7XqoVufvd/OSE7jYkmeDZIpuRKvV5XAAA",
  },
  "material-brass": {
    src: "/images/materials/material-brass.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZgCdAYs3DdALRQA/rQgngyPIsu6Sna8Q9ChrHQVdoqk0xbB5HFCSoeMLT6pgHW+NC4ttXXHVEUJk35aDW5FZrvryHX6yhyWgAAA",
  },
  "material-linen": {
    src: "/images/materials/material-linen.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAkAA4BaJZgCdAECsHoAAP145FLgUx3fMwO+UDe2Kq5dff2BMjheanpRTa8zy3Sx0/U7XqoVufvd/OSE7jYkmeDZIpuRKvV5XAAA",
  },
  "material-marble": {
    src: "/images/materials/material-marble.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCPOX+S8oAD+kb2GVdFV0/1MTw0pYveMRrlTOGRv55p7N2VSpK6T5IyaMSKOwDDnyhWsUkl0zGEsE4Ez5AAAAA==",
  },
  "material-oak": {
    src: "/images/materials/material-oak.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZgCdAYs3DdALRQA/rQgngyPIsu6Sna8Q9ChrHQVdoqk0xbB5HFCSoeMLT6pgHW+NC4ttXXHVEUJk35aDW5FZrvryHX6yhyWgAAA",
  },
  "material-terrazzo": {
    src: "/images/materials/material-terrazzo.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZgCdAYs3DdALRQA/rQgngyPIsu6Sna8Q9ChrHQVdoqk0xbB5HFCSoeMLT6pgHW+NC4ttXXHVEUJk35aDW5FZrvryHX6yhyWgAAA",
  },
  "material-walnut": {
    src: "/images/materials/material-walnut.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZgCdAYs3DdALRQA/rQgngyPIsu6Sna8Q9ChrHQVdoqk0xbB5HFCSoeMLT6pgHW+NC4ttXXHVEUJk35aDW5FZrvryHX6yhyWgAAA",
  },
  "prop-001": {
    src: "/images/properties/prop-001.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZgCdAYs3DdALRQA/rQgngyPIsu6Sna8Q9ChrHQVdoqk0xbB5HFCSoeMLT6pgHW+NC4ttXXHVEUJk35aDW5FZrvryHX6yhyWgAAA",
  },
  "prop-002": {
    src: "/images/properties/prop-002.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCPOX+S8oAD+kb2GVdFV0/1MTw0pYveMRrlTOGRv55p7N2VSpK6T5IyaMSKOwDDnyhWsUkl0zGEsE4Ez5AAAAA==",
  },
  "prop-003": {
    src: "/images/properties/prop-003.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAkAA4BaJZgCdAECsHoAAP145FLgUx3fMwO+UDe2Kq5dff2BMjheanpRTa8zy3Sx0/U7XqoVufvd/OSE7jYkmeDZIpuRKvV5XAAA",
  },
  "prop-004": {
    src: "/images/properties/prop-004.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAkAA4BaJZACdAEWR6FSEQAA4gIOXNDZyO/D1VJKCeU1OcEDM278ScWDVx8q6yFLyKVGnsfWqKMfojQZCTT2uwwaC1CnL4eqka6ItwBlrEVAAAA=",
  },
  "prop-005": {
    src: "/images/properties/prop-005.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAkAA4BaJZgCdAECsHoAAP145FLgUx3fMwO+UDe2Kq5dff2BMjheanpRTa8zy3Sx0/U7XqoVufvd/OSE7jYkmeDZIpuRKvV5XAAA",
  },
  "prop-006": {
    src: "/images/properties/prop-006.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAkAA4BaJZACdAEWR6FSEQAA4gIOXNDZyO/D1VJKCeU1OcEDM278ScWDVx8q6yFLyKVGnsfWqKMfojQZCTT2uwwaC1CnL4eqka6ItwBlrEVAAAA=",
  },
  "prop-007": {
    src: "/images/properties/prop-007.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAkAA4BaJZACdAEWR6FSEQAA4gIOXNDZyO/D1VJKCeU1OcEDM278ScWDVx8q6yFLyKVGnsfWqKMfojQZCTT2uwwaC1CnL4eqka6ItwBlrEVAAAA=",
  },
  "prop-008": {
    src: "/images/properties/prop-008.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAkAA4BaJZACdAEWR6FSEQAA4gIOXNDZyO/D1VJKCeU1OcEDM278ScWDVx8q6yFLyKVGnsfWqKMfojQZCTT2uwwaC1CnL4eqka6ItwBlrEVAAAA=",
  },
  "site-1": {
    src: "/images/sites/site-1.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAkAA4BaJZACdAEWR6FSEQAA4gIOXNDZyO/D1VJKCeU1OcEDM278ScWDVx8q6yFLyKVGnsfWqKMfojQZCTT2uwwaC1CnL4eqka6ItwBlrEVAAAA=",
  },
  "site-2": {
    src: "/images/sites/site-2.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCPOX+S8oAD+kb2GVdFV0/1MTw0pYveMRrlTOGRv55p7N2VSpK6T5IyaMSKOwDDnyhWsUkl0zGEsE4Ez5AAAAA==",
  },
  "site-3": {
    src: "/images/sites/site-3.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAkAA4BaJZgCdAECsHoAAP145FLgUx3fMwO+UDe2Kq5dff2BMjheanpRTa8zy3Sx0/U7XqoVufvd/OSE7jYkmeDZIpuRKvV5XAAA",
  },
  "trust-concept": {
    src: "/images/trust/trust-concept.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZgCdAYs3DdALRQA/rQgngyPIsu6Sna8Q9ChrHQVdoqk0xbB5HFCSoeMLT6pgHW+NC4ttXXHVEUJk35aDW5FZrvryHX6yhyWgAAA",
  },
  "trust-result": {
    src: "/images/trust/trust-result.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJZgCdAYs3DdALRQA/rQgngyPIsu6Sna8Q9ChrHQVdoqk0xbB5HFCSoeMLT6pgHW+NC4ttXXHVEUJk35aDW5FZrvryHX6yhyWgAAA",
  },
  "type-apartment": {
    src: "/images/onboarding/type-apartment.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAkAA4BaJQBOgCPOX+S8oAD+kb2GVdFV0/1MTw0pYveMRrlTOGRv55p7N2VSpK6T5IyaMSKOwDDnyhWsUkl0zGEsE4Ez5AAAAA==",
  },
  "type-farmhouse": {
    src: "/images/onboarding/type-farmhouse.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAkAA4BaJZgCdAECsHoAAP145FLgUx3fMwO+UDe2Kq5dff2BMjheanpRTa8zy3Sx0/U7XqoVufvd/OSE7jYkmeDZIpuRKvV5XAAA",
  },
  "type-penthouse": {
    src: "/images/onboarding/type-penthouse.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAkAA4BaJZACdAEWR6FSEQAA4gIOXNDZyO/D1VJKCeU1OcEDM278ScWDVx8q6yFLyKVGnsfWqKMfojQZCTT2uwwaC1CnL4eqka6ItwBlrEVAAAA=",
  },
  "type-villa": {
    src: "/images/onboarding/type-villa.avif",
    width: 1376,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAkAA4BaJZACdAEWR6FSEQAA4gIOXNDZyO/D1VJKCeU1OcEDM278ScWDVx8q6yFLyKVGnsfWqKMfojQZCTT2uwwaC1CnL4eqka6ItwBlrEVAAAA=",
  },
} as const satisfies Record<string, ImageAsset>;

export type ImageSlot = keyof typeof IMAGES;

export const imageFor = (slot: ImageSlot): ImageAsset => IMAGES[slot];
